#!/usr/bin/env python3 
# SPDX-License-Identifier: MIT
# ./build_pyz.py 
"""
Builds a "Lite" portable Python ZipApp (PYZ) using shiv.

All shiv builds generated by this script are 'lite' versions:
- Includes 'pdfium' for high-performance, lightweight PDF link extraction.
- Excludes 'PyMuPDF' to maintain a small footprint (approx. 5-8MB).
- Built from a temporary wheel to ensure a clean, reproducible bundle.
"""
from __future__ import annotations
import subprocess
import sys
import re
import os 
from pathlib import Path
import site
import pyhabitat
import tempfile
import shutil 

from build_executable import form_dynamic_name
from pdflinkcheck.datacopy import ensure_data_files_for_build
from pdflinkcheck._version import get_version

# Get the one site-packages path where packages are installed in the venv
SITE_PACKAGES_PATH = site.getsitepackages()[0]

# --- Configuration for pdflinkcheck ---
PROJECT_NAME = "pdflinkcheck"
ENTRY_POINT = "pdflinkcheck.cli:app"
DIST_DIR = Path("dist") / "zipapp" 
PROJECT_ROOT = Path(__file__).resolve().parent

# Ensure the output directory exists immediately
DIST_DIR.mkdir(parents=True, exist_ok=True)

# --- Build in Temp File to avoid issues namely on Windows ---
# Inside build_shiv_pyz()
build_temp = Path(tempfile.gettempdir()) / "shiv_build_pdflinkcheck"
if build_temp.exists():
    shutil.rmtree(build_temp, ignore_errors=True) # Force unlock/delete
build_temp.mkdir()

# Point shiv to use this specific temp directory
# (Shiv uses the environment variable SHIV_ROOT for its internal caching)
os.environ["SHIV_ROOT"] = str(build_temp)

# --- Helper Functions ---

def run_command(cmd, check=True, env=None):
    """Run command with printing and clear error reporting."""
    print(f"\n$ {' '.join(cmd)}")
    
    final_env = env if env is not None else os.environ

    result = subprocess.run(cmd, text=True, check=False, capture_output=True, env=final_env) 

    if result.stdout:
        print(result.stdout.strip())

    if result.returncode != 0:
        if result.stderr:
            print(f"--- COMMAND FAILED (Exit {result.returncode}) ---", file=sys.stderr)
            print(result.stderr.strip(), file=sys.stderr)
        
        if check:
            raise subprocess.CalledProcessError(
                result.returncode, cmd, output=result.stdout, stderr=result.stderr
            )
    return result

def find_latest_wheel(dist_dir: Path, version: str) -> Path:
    """Finds the most recently built wheel file for the given version."""
    wheels = sorted(
        dist_dir.glob(f"{PROJECT_NAME}-{version}*.whl"), 
        key=lambda f: f.stat().st_mtime,
        reverse=True
    )
    if not wheels:
        raise FileNotFoundError(f"No wheel found for version {version} in {dist_dir}.")
    return wheels[0]

def build_wheel():
    """
    Builds the source distribution and wheel using the standard Python build module.
    Handle Fdroid Termux sandboxing restrictions by building to a temp folder
    """
    print("\n1. Building project wheel using 'python -m build'...")
    # PASS THE CURRENT ENVIRONMENT (os.environ.copy())

    # Create a local tmp if on Termux to bypass no-exec restrictions
    custom_env = os.environ.copy()
    if pyhabitat.on_termux():
        termux_tmp = Path.home() / ".tmp"
        termux_tmp.mkdir(exist_ok=True)
        custom_env["TMPDIR"] = str(termux_tmp)
        print(f"Termux detected: Redirecting TMPDIR to {termux_tmp}")

    run_command(["uv", "build", 
        "--wheel", 
        "--out-dir", str(DIST_DIR)
    ], env=custom_env)

    print("Wheel build complete.")



def ensure_dependencies_and_shiv():
    """Ensures 'shiv', 'build', and all runtime dependencies are installed via uv."""

    if os.environ.get("CI") == "true":
        print("\n2. Skipping dependency check/install inside CI environment.")
        # We rely on the build.yml workflow to have already installed shiv, build, and project dependencies.
        # This prevents the script from calling 'uv' which isn't available.
        return
    
    # 2b. INSTALL/SYNC ALL PROJECT DEPENDENCIES (The Fix)
    print("Installing all project dependencies via uv pip install -e .")
    #run_command([sys.executable, "-m", "pip", "install", "-e", "."]) # will this install extras?
    #run_command([sys.executable, "-m", "pip", "install", "-e", ".[pdfium]"])
    run_command(["uv", "sync", "--extra", "pdfium", "--group", "dev"])

    # 2c. Ensure shiv is installed
    try:
        run_command(["uv", "run", "shiv", "--version"], check=True) 
    except subprocess.CalledProcessError:
        print("Installing 'shiv' ...")
        #run_command(["uv", "pip", "install", "shiv"])
        run_command([sys.executable, "-m", "pip", "install", "shiv"])
        #run_command([sys.executable, "-m", "pip", "install", "--upgrade", "shiv>=2.0.0"]) # pin shiv 1.0.8 in pyproject.toml for Termux
    print("Dependencies and shiv ready.")

def build_shiv_pyz():
    """Build the portable PYZ using shiv."""
    
    version = get_version()
    if version == "0.0.0":
        print("FATAL: Cannot proceed without a valid version found in pyproject.toml.", file=sys.stderr)
        sys.exit(1)
    
    # 1. Ensure dependencies, shiv, and build are ready
    ensure_dependencies_and_shiv()
    
    # 2. Build the wheel 
    build_wheel()
    

    # 3. Find the resulting wheel file
    wheel_path = find_latest_wheel(DIST_DIR, version)
    dynamic_name = form_dynamic_name(PROJECT_NAME, version)
    pyz_filename = f"{dynamic_name}-shiv.pyz" 
    interpreter = "python" if os.name == 'nt' else "/usr/bin/env python3"
    output_path = DIST_DIR / pyz_filename
    if output_path.exists():
        output_path.unlink()

    # SHIV COMMAND
    cmd = [
        "shiv", 
        "-o", str(output_path),
        "-p", interpreter, # Dynamic interpreter
        "-e", ENTRY_POINT,
        "--compressed",
        "--no-cache",
        #"--python", sys.executable, # removed for cross-platform robustness
        #"--site-packages", SITE_PACKAGES_PATH, # removed to prevent editable install conflicts # this makes the windows pyz huge ~100 MB
    ]

    # Clarify if PyMuPDF should be included or not
    # this determines which extra go inside of the PYZ
    whl_call = f"{str(wheel_path)}[pdfium]"  # include pdfium, not pymupdf, which won't package well into PYZ

    cmd.append(whl_call)    
    #cmd.insert[1](whl_call)
    
    # Pass the current, activated environment
    print(f"\n3. Building PYZ using shiv from Wheel: {pyz_filename}")
    run_command(cmd, env=os.environ.copy())
    
    output_path.chmod(0o755)

    # NEW: Cleanup the temporary wheel to keep dist/zipapp/ clean
    try:
        wheel_path.unlink()
        print(f"Removed build-wheel: {wheel_path.name}")
    except Exception as e:
        print(f"Note: Could not delete temporary wheel: {e}")
    
    print(f"\nBuild successful! Portable PYZ: {output_path.resolve()}")

    # 4. CREATE THE WINDOWS LAUNCHER (New Step)
    create_windows_bat_launcher(pyz_filename, DIST_DIR)

    return output_path

def create_windows_bat_launcher(pyz_filename: str, output_dir: Path):
    """
    Creates a Windows BAT file to launch the PYZ with the 'gui' command.
    Only runs if the current OS is Windows.
    """
    if os.name != 'nt': # 'nt' is the name for Windows
        return
    
    bat_filename = pyz_filename.replace(".pyz", "-gui.bat")
    bat_path = output_dir / bat_filename
    
    # The content of the batch file
    # @echo off: Hides the commands themselves
    # python "%~dp0{pyz_filename}" gui: Executes the PYZ with the 'gui' command.
    # %~dp0 ensures the path to the PYZ is correct regardless of where the bat is launched from.
    bat_content = f"""@echo off
rem Launch {pyz_filename} with the 'gui' command using the system's python.
python "%~dp0{pyz_filename}" gui
"""
    
    try:
        bat_path.write_text(bat_content, encoding="utf-8")
        print(f"Created Windows BAT launcher: {bat_path.name}")
    except Exception as e:
        print(f"WARNING: Failed to create BAT launcher: {e}", file=sys.stderr)

if __name__ == "__main__":
    try:
        # Ensure data files are available to build package
        ensure_data_files_for_build()
        # NOTE: This script is intended to be run via: uv run python build_pyz.py
        path = build_shiv_pyz()
    except subprocess.CalledProcessError as e: 
        print(f"\nFATAL ERROR: A subprocess failed with exit code {e.returncode}.", file=sys.stderr)
        print("Review the stderr output above for details (often a dependency issue).", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"\nFATAL ERROR during PYZ build: {e}", file=sys.stderr)
        sys.exit(1)

    #   Test for success
    try:
        print("Testing the Shiv artifact...")
        run_command([sys.executable, str(path), "--help"], check=True)
        if pyhabitat.tkinter_is_available():
            #try:
            print(f"Testing GUI for {str(path)}...")
            run_command([sys.executable, str(path), "gui", "--auto-close", "1000"], check=True)
            #except Exception as e:
            #    print(f"Error launching gui: {e}")
        print("Testing complete.")
    except Exception as e:
        print(f"\n ERROR during PYZ post-build test: {e}", file=sys.stderr)
        sys.exit(1)
    
