# syntax=docker/dockerfile:1.4
ARG PYTHON_VERSION=3.11-slim  # Change to slim (Debian-based)

FROM python:${PYTHON_VERSION}

WORKDIR /app

# Install essential runtime packages (git/curl/bash are useful for dev)
RUN apt-get update \
    && apt-get install -y --no-install-recommends bash curl git \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install --no-cache-dir setuptools wheel \
    && pip install --no-cache-dir -e .
#    && pip install --no-cache-dir -e ".[full]"

EXPOSE 8000

ENTRYPOINT ["/bin/bash"]

LABEL org.opencontainers.image.source=https://github.com/city-of-memphis-wastewater/pdflinkcheck
LABEL org.opencontainers.image.description="Developer environment for pdflinkcheck, a CLI and GUI that leverages the PyMuPDF library to inspect PDF files for internal links, external links, and table of contents (toc)."
